import os
import json
import time
import uuid
import numpy as np
from flask import Flask, render_template, request, jsonify
from flask_cors import CORS
from werkzeug.utils import secure_filename
from mega import Mega
import key

app = Flask(__name__)
CORS(app)

# Configuration
UPLOAD_FOLDER = 'temp_uploads'
os.makedirs(UPLOAD_FOLDER, exist_ok=True)

# Initialize MEGA
try:
    mega = Mega()
    m = mega.login(key.MEGA_EMAIL, key.MEGA_PASSWORD)
    print("Logged into MEGA successfully")
except Exception as e:
    print(f"MEGA Login Failed: {e}")
    m = None

def extract_keypoints_from_json(landmarks_data):
    """
    Converts JS landmarks to Numpy array matching the Python implementation.
    Format: Concatenated Left Hand (21*3) + Right Hand (21*3).
    Returns: np.array of shape (126,)
    """
    # Initialize empty arrays
    lh = np.zeros(21*3)
    rh = np.zeros(21*3)

    # Helper to flatten list of dicts [{'x':...}, ...] -> [x1, y1, z1, x2...]
    def flatten_hand(hand_data):
        if not hand_data:
            return np.zeros(21*3)
        flat = []
        for lm in hand_data:
            flat.extend([lm.get('x', 0), lm.get('y', 0), lm.get('z', 0)])
        return np.array(flat)

    if 'left' in landmarks_data and landmarks_data['left']:
        lh = flatten_hand(landmarks_data['left'])
    
    if 'right' in landmarks_data and landmarks_data['right']:
        rh = flatten_hand(landmarks_data['right'])
        
    return np.concatenate([lh, rh])

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/upload', methods=['POST'])
def upload_data():
    if not m:
        return jsonify({'error': 'Server storage not configured (MEGA login failed)'}), 500

    try:
        # 1. Parse Form Data
        session_id = request.form.get('session_id')
        action = request.form.get('action')
        sequence_id = request.form.get('sequence_id') # Generated by frontend or backend
        timestamp = int(time.time())
        
        # 2. Get Files
        video_raw = request.files.get('video_raw')
        video_overlay = request.files.get('video_overlay')
        landmarks_json_file = request.files.get('landmarks')
        metadata_json_file = request.files.get('metadata')

        if not all([video_raw, video_overlay, landmarks_json_file]):
            return jsonify({'error': 'Missing files'}), 400

        # 3. Create Local Temp Structure
        folder_name = f"{action}_{timestamp}_{session_id[:8]}"
        temp_dir = os.path.join(UPLOAD_FOLDER, folder_name)
        os.makedirs(temp_dir, exist_ok=True)
        
        # Save Videos
        raw_path = os.path.join(temp_dir, 'video_raw.webm')
        overlay_path = os.path.join(temp_dir, 'video_overlay.webm')
        video_raw.save(raw_path)
        video_overlay.save(overlay_path)

        # Save Metadata
        meta_path = os.path.join(temp_dir, 'metadata.json')
        if metadata_json_file:
            metadata_json_file.save(meta_path)

        # Process Landmarks to Numpy
        landmarks_path = os.path.join(temp_dir, 'landmarks')
        os.makedirs(landmarks_path, exist_ok=True)
        
        landmarks_data = json.load(landmarks_json_file)
        # Expected landmarks_data is a list of 40 frames
        
        for i, frame_data in enumerate(landmarks_data):
            if i >= 40: break # Ensure max 40 frames
            npy_data = extract_keypoints_from_json(frame_data)
            np.save(os.path.join(landmarks_path, f"{i}.npy"), npy_data)

        # 4. Upload to MEGA
        # Create folder in MEGA: CODEWAVE_ROOT/{timestamp}_{session_id}
        root_folder = m.find('CODEWAVE_DATA_COLLECTION')
        if not root_folder:
            m.create_folder('CODEWAVE_DATA_COLLECTION')
            root_folder = m.find('CODEWAVE_DATA_COLLECTION')
        
        session_folder_name = f"{timestamp}_{session_id}"
        session_folder = m.create_folder(session_folder_name, root_folder[0])
        
        # Upload videos
        m.upload(raw_path, session_folder[0])
        m.upload(overlay_path, session_folder[0])
        m.upload(meta_path, session_folder[0])
        
        # Upload numpy files (create subfolder first)
        npy_folder = m.create_folder('landmarks', session_folder[0])
        for filename in os.listdir(landmarks_path):
            m.upload(os.path.join(landmarks_path, filename), npy_folder[0])

        # Cleanup Local Files
        import shutil
        shutil.rmtree(temp_dir)

        return jsonify({'status': 'success', 'message': 'Upload complete'})

    except Exception as e:
        print(f"Error processing upload: {e}")
        return jsonify({'error': str(e)}), 500

if __name__ == '__main__':
    app.run(debug=True, port=5000)